name: Run Python Script

on:
  workflow_dispatch

env:
  SMS_SENDER_ADDRESS: ${{ secrets.SMS_SENDER_ADDRESS }}
  SMS_SENDER_PASSWORD: ${{ secrets.SMS_SENDER_PASSWORD }}
  SMS_RECIPIENT_PHONE_NUMBER: ${{ secrets.SMS_RECIPIENT_PHONE_NUMBER }}
  SMS_PROVIDER: ${{ secrets.SMS_PROVIDER }}

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run App
        run:
          python main.py